services:
  react:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./react-app:/src
    environment:
      - WATCHPACK_POLLING=true
    tty: true

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python
    ports:
      - "4000:4000"
    volumes:
      - ./python:/src
    depends_on:
      - react
    tty: true
