services:
  react:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./react-app:/src
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    command: /bin/bash -c "npm i && HTTPS=true npm run start"

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python
    ports:
      - "4000:4000"
    volumes:
      - ./python:/src
    depends_on:
      - react
    tty: true
    command: /bin/bash -c "poetry install --no-root && bash crt/issue_crt.sh 192.168.10.10 && cd api && python3  migrate_db.py && python3 main.py"

#   db:
#     build:
#       context: .
#       dockerfile: Dockerfile # カスタム Dockerfile を使用
#     platform: linux/x86_64 # M1 Mac 環境で必要
#     environment:
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # root アカウントをパスワードなしで作成
#       MYSQL_DATABASE: 'demo' # 初期データベースとして demo を設定
#       TZ: 'Asia/Tokyo' # タイムゾーンを日本時間に設定
#     volumes:
#       - mysql_data:/var/lib/mysql # 永続化データ用ボリューム
#     ports:
#       - 33306:3306 # ホストのポート 33306 をコンテナの 3306 にマッピング

# volumes:
#   mysql_data:
