name: python actions

on:
  push:
    paths:
      - 'python/**/*.py'
      - 'python/poetry.lock'
      - 'python/pyproject.toml'

  workflow_dispatch:
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t python .
          
      - name: Start a container
        run: docker run --rm -v $(pwd):/app -w /app python poetry install --no-root && poetry show && pytest
