name: Build and Cache Docker Image

on:
  push:
    paths:
      - 'react-app/**'
      - 'react-app/Dockerfile'
      - '.github/workflows/python_actions.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make directory for Docker cache
        run: mkdir -p ~/.docker/cache

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./react-app
          file: ./react-app/Dockerfile
          push: false
          tags: react-app:latest
          cache-from: type=local,source=${{ github.workspace }}/.docker/cache
          cache-to: type=local,dest=${{ github.workspace }}/.docker/cache

      - name: Run Docker container
        run: |
          docker run --rm react-app:latest npm install && npm run lint