name: python actions

on:
  push:
    paths:
      - 'python/**/*.py'
      - 'python/poetry.lock'
      - 'python/pyproject.toml'
      - '.github/workflows/python_actions.yml'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create dir for cache
        run: mkdir -p $HOME/.cache/pypoetry

      - name: Set up Docker cache for poetry
        uses: actions/cache@v3
        id: cache
        with:
          path: $HOME/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('python/poetry.lock', 'python/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Build Docker image
        run: |
          docker build -t python .
      
      - name: Start and run tests
        run: |
          docker run --rm -v $(pwd):/app -w /app python sh -c "poetry run pytest"

      - name: Save Docker cache for poetry
        uses: actions/cache@v3
        with:
          path: $HOME/.cache/pypoetry
          key: ${{ steps.cache.outputs.cache-primary-key }}