name: Build and Cache Docker Image

on:
  push:
    paths:
      - 'react-app/**'
      - 'react-app/Dockerfile'
      - '.github/workflows/python_actions.yml'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make directory for Docker cache
        run: mkdir -p $HOME/.cache/python

      - name: show directory
        run: |
          ls -la .
          ls -la $HOME/
          ls -la $HOME/.cache


      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: $HOME/.cache/python
          key: ${{ runner.os }}-python-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: python:latest
          cache-from: type=local,source=$HOME/.cache/python
          cache-to: type=local,dest=$HOME/.cache/python

      - name: Run Docker container
        run: |
          docker run --rm react-app:latest npm install && npm run lint

      - name: show directory
        run: |
          ls -la .
          ls -la $HOME/
          ls -la $HOME/.cache