name: python actions

on:
  push:
    paths:
      - 'react-app/**'
      - 'react-app/Dockerfile'
      - '.github/workflows/python_actions.yml'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-python-${{ hashFiles('python/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-python-

      - name: Build Docker image
        id: build
        run: |
          pwd && ls -al
          docker buildx build --file python/Dockerfile --tag app:latest --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache-new --progress=plain python/

      - name: List Docker images (for debugging)
        run: |
          docker images
          docker buildx ls
          docker ps -a

      - name: Run Docker container with pytest
        run: |
          docker run --rm -v $(pwd)/python:/app -w /app app:latest pytest
          
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache