name: Build and Cache Docker Image

on:
  push:
    paths:
      - 'react-app/**'
      - 'react-app/Dockerfile'
      - '.github/workflows/python_actions.yml'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./python
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: list ls
        run: ls -al
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-python-${{ hashFiles('./Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-python-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: python
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Run Docker container
        run: |
          docker run --rm python pytest
      
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache