name: python actions

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
    paths:
      - 'python/**/*.py'

  workflow_dispatch:
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t python .
          
      - name: Start a container
        run: docker run --rm -v $(pwd):/app -w /app python python3 pytest
