name: react-app actions

on:
  push:
    paths:
      - 'react-app/**/*.tsx'
      - 'react-app/**/*.ts'
      - 'react-app/package*.json'
      - '.github/workflows/react-app_actions.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-react-${{ hashFiles('react-app/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-react-

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: react-app/
          file: react-app/Dockerfile
          push: false
          tags: react
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache-react
          cache-to: type=local,dest=/tmp/.buildx-cache-react-new

      - name: Run Docker container with linter
        run: |
          docker run --rm -v $(pwd)/python:/app -w /app react npm install && npm run lint
          
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-cache-react
          mv /tmp/.buildx-cache-react-new /tmp/.buildx-cache-react
  
  type-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-react-${{ hashFiles('react-app/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-react-

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: react-app/
          file: react-app/Dockerfile
          push: false
          tags: react
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache-react
          cache-to: type=local,dest=/tmp/.buildx-cache-react-new

      - name: Run Docker container with type-check
        run: |
          docker run --rm -v $(pwd)/python:/app -w /app react npm install && npm run type-check
          
      - name: Move caches
        run: |
          rm -rf /tmp/.buildx-cache-react
          mv /tmp/.buildx-cache-react-new /tmp/.buildx-cache-react