name: react-app actions

on:
  push:
    paths:
      - 'react-app/**/*.tsx'
      - 'react-app/**/*.ts'
      - 'react-app/package*.json'

  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker chache for npm
        uses: actions/ache@v3
        with:
          path: /root/.chache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('react-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Build Docker image
        run: docker build -t react .
          
      - name: Start a container
        run: docker run --rm -v $(pwd):/app -w /app react npm i && npm run lint

  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker chache for npm
        uses: actions/ache@v3
        with:
          path: /root/.chache/npm
          key: ${{ runner.os }}-npm-${{ hashFiles('react-app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
              
      - name: Build Docker image
        run: docker build -t react .
          
      - name: Start a container
        run: docker run --rm -v $(pwd):/app -w /app react npm i && npm run type-check