name: react-app actions

on:
  push:
    paths:
      - 'react-app/**/*.tsx'
      - 'react-app/**/*.ts'
      - 'react-app/package*.json'

  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t react .
          
      - name: Start a container
        run: docker run --rm -v $(pwd):/app -w /app react npm run lint

  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t react .
          
      - name: Start a container
        run: docker run --rm -v $(pwd):/app -w /app react npm run type-check